<!-- await keyword
await on the promise as it will always wait for this promise to be resolved/reject and once its fulfilled 
await returns the resolved value of the fulfilled promise -->
<!-- thatas how we write noramllly but if we want to find error thten need to add tey and catch with silghtly different oreder of syntax  -->
<script>
    async function getTodoItem(){

        // fetch("https://jsonplaceholder.typicode.com/todos/1").then((response) =>{
        //     return response.json();
        // }).then((data) =>{
        //     console.log(data);
        // });

        const response = await fetch("https://jsonplaceholder.typicode.com/todos/1");   //await keyword will return us the resolved value of fetch which is response (also fetch always retuns a prommise)  
        const data = await response.json();                     //now response.json() will return us the new promise and now again we used await and it will return us the resolved value of response.json() (promise) which is data.  (can caopare it to the above code as output is samew for both but await one is simpler and clean to understand)
        console.log(data); 
    }

    getTodoItem();
</script>